In [1]:
import pandas as pd
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
df = pd.DataFrame(data)
display(df) 
print(df.loc[0])

   calories  duration
0       420        50
1       380        40
2       390        45

calories    420
duration     50
Name: 0, dtype: int64

In [2]:
import pandas as pd
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
display(df) 
display(df.loc[["day1","day3","day2"]])

      calories  duration
day1       420        50
day2       380        40
day3       390        45

      calories  duration
day1       420        50
day3       390        45
day2       380        40

In [3]:
import pandas as pd
data = [
    {"calories": 420, "duration": 50},
    {"calories": 380, "duration": 40},
    {"calories": 390, "duration": 45}
]
df = pd.DataFrame(data, index=["day1", "day2", "day3"])
display(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [4]:
import pandas as pd
data = [
    [420, 50],
    [380, 40],
    [390, 45]
]
df = pd.DataFrame(data, columns=["calories", "duration"], index=["day1", "day2", "day3"])
display(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [5]:
import pandas as pd
df=pd.read_csv('tips.csv')
display(df.loc[[1,4]])

   total_bill   tip     sex smoker  day    time  size
1       10.34  1.66    Male     No  Sun  Dinner     3
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
import pandas as pd
df=pd.read_csv('tips.csv')
display(df.head(3))
df.info()
rows ,cols=df.shape
print(rows,cols)
df.describe()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB
244 7

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [7]:
import pandas as pd
df=pd.read_csv('tips.csv')
df.loc[0]
df.loc[0:3 ,["size" ,"tip"]]
df.iloc[1,3]

'No'

In [11]:
import pandas as pd
df=pd.read_csv('tips.csv')
display(df.iloc[0:5, [0,1]])
display(df.at[0,"sex"])
df.iat[9,6]

   total_bill   tip
0       16.99  1.01
1       10.34  1.66
2       21.01  3.50
3       23.68  3.31
4       24.59  3.61

'Female'

np.int64(2)

In [14]:
import pandas as pd
df=pd.read_csv('tips.csv')
display(df.at[0,"total_bill"])
display(df.iat[4,1])
display(df.iloc[10:15 ,[0,1]])
tt=df.loc[df['day'] == 'Sun', 'total_bill'] = df['total_bill'] * 0.90
display(tt)

np.float64(16.99)

np.float64(3.61)

    total_bill   tip
10       10.27  1.71
11       35.26  5.00
12       15.42  1.57
13       18.43  3.00
14       14.83  3.02

0      15.291
1       9.306
2      18.909
3      21.312
4      22.131
        ...
239    26.127
240    24.462
241    20.403
242    16.038
243    16.902
Name: total_bill, Length: 244, dtype: float64